---
    - name: ubuntu-install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes

    - name: ubuntu-GPG key
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
    - name: ubuntu-repository docker
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"  
        state: present
    - name: ubuntu-install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    - name: ubuntu-Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: /home/ubuntu
        mode: '755'
